name: REST API Trigger for C Code

on:
  workflow_dispatch:
    inputs:
      code:
        description: "The C code to compile and run"
        required: true

jobs:
  api_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Fetch and display the code
      - name: Fetch code from API request payload
        run: |
          echo "The following code was passed via API:"
          echo "${{ github.event.inputs.code }}"
      
      # Step 3: Write the code to a file
      - name: Write code to file
        run: |
          echo "${{ github.event.inputs.code }}" > loop_code.c

      # Step 4: Compile and run the code
      - name: Compile and run C code
        run: |
          gcc loop_code.c -o loop_code
          ./loop_code
