name: REST API Trigger for C Code

on:
  workflow_dispatch:
    inputs:
      code:
        description: "The C code to compile and run"
        required: true
        default: "#include <stdio.h>\nint main() {\n for(int i = 1; i <= 10; i++) { printf(\"%d\\n\", i); }\n return 0;\n}"

jobs:
  api_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Process the API request's posted code
      - name: Fetch code from API request payload
        run: |
          echo "The following code was passed via API:"
          echo "${{ github.event.inputs.code }}"
      
      # Step 3: Save the passed code into a file (properly escaping quotes in printf)
      - name: Write code to file
        run: |
          echo "${{ github.event.inputs.code }}" > loop_code.c

      # Step 4: Compile and Run the Submitted C Code
      - name: Compile and Run C Code
        run: |
          gcc loop_code.c -o loop_code
          ./loop_code
