name: REST API Trigger for C Code

on:
  workflow_dispatch:
    inputs:
      code:
        description: "The C code to compile and run"
        required: true
        default: "#include <stdio.h>\nint main() {\n for(int i = 1; i <= 10; i++) { printf(\\\"%d\\n\\\", i); }\n return 0;\n}"

jobs:
  api_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Write the submitted code into a file (from API input)
      - name: Write code to file
        run: |
          echo "${{ github.event.inputs.code }}" > loop_code.c

      # Step 3: Compile the C code
      - name: Compile C Code
        run: |
          gcc loop_code.c -o loop_code

      # Step 4: Run the compiled code and capture output
      - name: Run C Code
        run: |
          echo "Running the C code:"
          ./loop_code

      # Step 5: Verify if output prints numbers 1 to 10
      - name: Verify Output
        run: |
          OUTPUT=$(./loop_code)
          echo "Output from C Program:"
          echo "$OUTPUT"
          if [[ "$OUTPUT" == "1\n2\n3\n4\n5\n6\n7\n8\n9\n10" ]]; then
            echo "C code executed correctly, printed numbers 1 to 10"
          else
            echo "C code did not execute as expected"
            exit 1
          fi
